config/routes.rb
Menyou::Application.routes.draw do

	resources :categories
	resources :chefs
	resources :comments do
		member do
			get :read
			get :unread
		end
	end
	resources :items
	resources :photos
	resources :sessions

	root to: 'pages#home'

	# Pages
	match '/about' => 'pages#about', as: :about
	match '/menu' => 'pages#menu', as: :menu
	match '/test' => 'pages#test', as: :test
	match '/test-upload' => 'pages#test_upload', as: :test_upload

	# Photos
	match '/gallery' => 'photos#gallery', as: :gallery
	match '/upload' => 'photos#upload', as: :upload
	match '/upload-photo' => 'photos#upload_photo', as: :upload_photo

	# Sessions
	match '/sign-in' => 'sessions#new', as: :signin
	match '/sign-out' => 'sessions#destroy', as: :signout
end

app/models/comment.rb
class Comment < ActiveRecord::Base
 	attr_accessible :email, :content
 	
 	validates :email, presence: true
	validates :content, presence: true, length: { maximum: 255, minimum: 1 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :authenticate, except: :create

	def index
		@title = 'Comments'
		@read = Comment.where('read = ?', true).order('created_at DESC')
		@unread = Comment.where('read = ?', false).order('created_at ASC')
	end

	def create
		@comment = Comment.new(params[:comment])
		if @comment.save!
			respond_to do |format|
				format.html { redirect_to root_path }
				format.js
			end
		else
			redirect_to root_path
		end
	end

	def destroy
		Comment.find(params[:id]).destroy
		flash[:notice] = 'Comment deleted'
		redirect_to comments_path
	end

	def read
		comment = Comment.find(params[:id])
		comment.read = true
		comment.save
		flash[:success] = 'Comment read'
		redirect_to comments_path
	end

	def unread
		comment = Comment.find(params[:id])
		comment.read = false
		comment.save
		flash[:success] = 'Comment unread'
		redirect_to comments_path
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="pendingComment">
	<div class="commentCreated">
		<%= comment.created_at.strftime('%b %d, %y - %I:%M %p') %>
	</div>
	<div class="pendingCommentName">
		<p><%= comment.email %></p>
	</div>
	<p><%= comment.content %></p>
	<div class="commentApprove">
		<% if comment.read? %>
			<%= link_to 'Unread', unread_comment_path(comment) %>
		<% else %>
			<%= link_to 'Read', read_comment_path(comment) %>
		<% end %>
		| <%= link_to 'Delete', comment, method: :delete, confirm: 'Delete?' %>
	</div>
</div>

app/views/comments/_comment_confirm.html.erb
<div class="commentFormHeader">
	<div class="commentFormToggle">
		<div class="commentFormHide"></div>
	</div>
	<div class="clear"></div>
</div>
<div class="commentConfirm">
	<p>Thank you for taking your time and contacting us.</p>
	<p>Customer service is our number one priority.</p>
	<p>Your thoughts are very important, we will reply to you as soon as possible.</p>
</div>

app/views/comments/_comment_form.html.erb
<div class="commentFormHeader">
	<h1>Contact Us</h1>
	<div class="commentFormToggle">
		<div class="commentFormShow"></div>
		<div class="commentFormHide"></div>
	</div>
	<div class="clear"></div>
</div>
<%= form_for(Comment.new, remote: true) do |f| %>
	<div class="field">
		<p>Email</p>
		<%= f.text_field :email, autocomplete: 'off' %>
	</div>
	<div class="field">
		<%= f.text_area :content %>
	</div>
	<div class="action">
		<%= f.submit 'Submit' %>
		<div class="commentCounter">
			255
		</div>
		<div class="clear"></div>
	</div>
<% end %>

app/views/comments/create.js.erb
$('.commentForm').animate({ bottom: '-=241' }, 500, function() {
	$(this).html("<%= escape_javascript(render(partial: 'comments/comment_confirm')) %>");
	$(this).animate({ bottom: '+=241' }, 500);
	$('.commentFormHide').show();
})

app/views/comments/index.html.erb
<div class="comments">
	<div class="approved">
		<%= render partial: 'comments/comment', collection: @read, as: :comment %>
	</div>
	<div class="pending">
		<%= render partial: 'comments/comment', collection: @unread, as: :comment %>
	</div>
	<div class="clear"></div>
</div>