config/routes.rb
Menyou::Application.routes.draw do

	resources :categories
	resources :chefs
	resources :comments do
		member do
			get :read
			get :unread
		end
	end
	resources :items
	resources :photos
	resources :sessions

	root to: 'pages#home'

	# Pages
	match '/about' => 'pages#about', as: :about
	match '/menu' => 'pages#menu', as: :menu
	match '/test' => 'pages#test', as: :test
	match '/test-upload' => 'pages#test_upload', as: :test_upload

	# Photos
	match '/gallery' => 'photos#gallery', as: :gallery
	match '/upload' => 'photos#upload', as: :upload
	match '/upload-photo' => 'photos#upload_photo', as: :upload_photo

	# Sessions
	match '/sign-in' => 'sessions#new', as: :signin
	match '/sign-out' => 'sessions#destroy', as: :signout
end

app/models/chef.rb
class Chef < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_attached_file :image,
                    default_url: '/assets/default.jpg',
                    storage: :s3,
                    s3_credentials: "#{Rails.root}/config/s3.yml",
                    path: "/chefs/:style/:id/:filename"

  attr_accessible :image, :info, :name

  validates :info, presence: true
  validates :name, presence: true
  validates_uniqueness_of :name

  def deletable?
    true if Chef.find_by_id(self.id)
  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_filter :authenticate, except: :index

  def index
    @title = 'Chefs'
    @chefs = Chef.order('name ASC')
  end

  def new
    @title = 'New Chef'
    @chef = Chef.new
  end

  def create
    @chef = Chef.new(params[:chef])
    if @chef.save
      flash[:success] = 'Chef created'
      redirect_to chefs_path
    else
      @title = 'New Chef'
      render 'new'
    end
  end

  def edit
    @chef = Chef.find(params[:id])
    @title = "Edit #{@chef.name}"
    render 'new'
  end

  def update
    @chef = Chef.find(params[:id])
    if @chef.update_attributes(params[:chef])
      flash[:success] = 'Chef updated'
      redirect_to chefs_path
    else
      @title = "Edit #{@chef.name}"
      render 'new'
    end
  end

  def destroy
    Chef.find(params[:id]).destroy
    flash[:notice] = 'Chef deleted'
    redirect_to chefs_path
  end
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/views/chefs/_chef.html.erb
<div class="chefName">
    <% if signed_in? %>
        <%= link_to chef.name, edit_chef_path(chef) %>
    <% else %>
        <%= chef.name %>
    <% end %>
</div>
<div class="chef">
    <div class="chefImage">
        <%= image_tag chef.image.url %>
    </div>
    <div class="chefInfo">
        <%= to_html(chef.info) %>
    </div>
    <div class="clear"></div>
</div>

app/views/chefs/index.html.erb
<%= render @chefs %>

app/views/chefs/new.html.erb
<%= form_for @chef, html: { multipart: true } do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
        <p>Name</p>
        <%= f.text_field :name, autocomplete: :off %>
    </div>
    <div class="field">
        <p>Info</p>
        <%= f.text_area :info %>
    </div>
    <div class="field">
        <p>Image</p>
        <%= f.file_field :image %>
    </div>
    <div class="action">
        <%= f.submit 'Submit' %>
        <%= link_to 'Cancel', chefs_path %>
        <% if @chef.deletable? %>
            <%= link_to 'Delete', @chef, method: :delete, confirm: 'Delete chef?' %>
        <% end %>
    </div>
<% end %>