config/routes.rb
Menyou::Application.routes.draw do

	resources :categories
	resources :chefs
	resources :comments do
		member do
			get :read
			get :unread
		end
	end
	resources :items
	resources :photos
	resources :sessions

	root to: 'pages#home'

	# Pages
	match '/about' => 'pages#about', as: :about
	match '/menu' => 'pages#menu', as: :menu
	match '/test' => 'pages#test', as: :test
	match '/test-upload' => 'pages#test_upload', as: :test_upload

	# Photos
	match '/gallery' => 'photos#gallery', as: :gallery
	match '/upload' => 'photos#upload', as: :upload
	match '/upload-photo' => 'photos#upload_photo', as: :upload_photo

	# Sessions
	match '/sign-in' => 'sessions#new', as: :signin
	match '/sign-out' => 'sessions#destroy', as: :signout
end

app/models/item.rb
class Item < ActiveRecord::Base

	has_attached_file :image,
          				  default_url: '/assets/default.jpg',
          				  storage: :s3,
          				  s3_credentials: "#{Rails.root}/config/s3.yml",
          				  path: "/:style/:id/:filename"

  	attr_accessible :category_id, :image, :info, :large_price, 
  					:name, :small_price, :spicy

  	belongs_to :category

  	validates :name, presence: true
  	validates_uniqueness_of :name
  	validates :category_id, presence: true

    default_scope order: 'name ASC'

    def deletable?
    	true if Item.find_by_id(self.id)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_filter :authenticate

	def new
		@title = 'New Item'
		@item = Item.new
	end

	def create
		@item = Item.new(params[:item])
		if @item.save
			flash[:success] = "#{@item.name} created"
			redirect_to new_item_path
		else
			@title = 'New Item'
			render 'new'
		end
	end

	def edit
		@item = Item.find(params[:id])
		@title = "Edit #{@item.name}"
		render 'new'
	end

	def update
		@item = Item.find(params[:id])
		if @item.update_attributes(params[:item])
			flash[:success] = 'Item updated'
			redirect_to @item.category
		else
			@title = "Edit #{@item.name}"
			render 'new'
		end
	end

	def destroy
		item = Item.find(params[:id])
		item.destroy
		flash[:notice] = 'Item deleted'
		redirect_to new_item_path
	end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item.html.erb
<div class="item <%= cycle('odd', 'even') %>">
	<div class="itemImage">
		<div>
			<%= link_to(item.image.url, title:"#{item.name}") do %>
				<%= image_tag '/assets/default.jpg', class: 'lazyLoad', 'data-original' => item.image.url %>
			<% end %>
		</div>
	</div>
	<div class="itemName">
		<% if signed_in? %>
			<p><%= link_to item.name, edit_item_path(item), title: 'Edit item' %></p>
		<% else %>
			<p><%= item.name %></p>
		<% end %>
	</div>
	<div class="itemPrice">
		<% if !item.small_price.blank? %>
			<div class="largePrice">
				L: <b><%= number_to_currency(item.large_price) %></b>
			</div>
			<div class="smallPrice">
				S: <b><%= number_to_currency(item.small_price) %></b>
			</div>
		<% elsif !item.large_price.blank? %>
			<div class="largePrice">
				<b><%= number_to_currency(item.large_price) %></b>
			</div>
		<% end %>
		<% if item.spicy? %>
			<div class="spicy">
				Spicy
			</div>
		<% end %>
	</div>
</div>

app/views/items/new.html.erb
<%= form_for @item, html: { multipart: true } do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<p>Name</p>
		<%= f.text_field :name, autocomplete: :off %>
	</div>
	<div class="field">
		<p>Price (Large Price)</p>
		<%= f.text_field :large_price %>
	</div>
	<div class="field">
		<p>Small Price</p>
		<%= f.text_field :small_price %>
	</div>
	<div class="field">
		<p>Category</p>
		<%= f.select :category_id, category_list %>
	</div>
	<div class="field">
		<p>Spicy</p>
		<%= f.check_box :spicy %>
	</div>
	<div class="field">
		<p>Image</p>
		<%= f.file_field :image %>
	</div>
	<div class="field">
		<p>Description</p>
		<%= f.text_area :info %>
	</div>
	<div class="action">
		<%= f.submit 'Submit' %>
		<% if @item.category %>
			<%= link_to 'Cancel', @item.category %>
		<% else %>
			<%= link_to 'Cancel', menu_path %>
		<% end %>
		<% if @item.deletable? %>
			<%= link_to 'Delete', @item, method: :delete, confirm: 'Delete?' %>
		<% end %>
	</div>
<% end %>