config/routes.rb
Menyou::Application.routes.draw do

	resources :categories
	resources :chefs
	resources :comments do
		member do
			get :read
			get :unread
		end
	end
	resources :items
	resources :photos
	resources :sessions

	root to: 'pages#home'

	# Pages
	match '/about' => 'pages#about', as: :about
	match '/menu' => 'pages#menu', as: :menu
	match '/test' => 'pages#test', as: :test
	match '/test-upload' => 'pages#test_upload', as: :test_upload

	# Photos
	match '/gallery' => 'photos#gallery', as: :gallery
	match '/upload' => 'photos#upload', as: :upload
	match '/upload-photo' => 'photos#upload_photo', as: :upload_photo

	# Sessions
	match '/sign-in' => 'sessions#new', as: :signin
	match '/sign-out' => 'sessions#destroy', as: :signout
end

app/views/layouts/_footer.html.erb
<div class="copyright">
	<p>Golden Dragon Vista of California</p>
</div>

app/views/layouts/_header.html.erb
<div class="topHeader"></div>
<div class="socialMedia">
	<div class="yelp">
		<%= link_to('http://www.yelp.com/biz/golden-dragon-vista', target: '_blank') do %>
			<%= image_tag '/assets/yelp.png' %>
		<% end %>
	</div>
	<div class="facebook">
		<div class="fb-like" data-send="false" data-width="450" data-show-faces="false" data-font="arial" data-href="<%= root_url %>"></div>
	</div>
	<div class="twitter">
		<a href="https://twitter.com/share" class="twitter-share-button" data-related="jasoncosta" data-lang="en" data-size="small" data-count="none" data-url="<%= @short.shorten(request.url).shorturl %>" %>">Tweet</a>
	</div>
</div>
<% if signed_in? %>
	<div class="adminNav">
		<ul>
			<li><%= link_to 'New Item', new_item_path %></li>
			<li><%= link_to 'New Photo', upload_path %></li>
			<li><%= link_to 'New Chef', new_chef_path %></li>
			<li><%= link_to 'Categories', new_category_path %></li>
			<li><%= link_to 'Comments', comments_path %></li>
			<li><%= link_to 'Sign Out', signout_path %></li>
		</ul>
	</div>
<% end %>
<div class="bottomHeader">
	<div class="headerNav">
		<div class="leftNav">
			<%= link_to 'SIFU', chefs_path %>
			<%= link_to 'ABOUT', about_path %>
		</div>
		<div class="rightNav">
			<%= link_to 'MENU', menu_path %>
			<%= link_to 'GALLERY', gallery_path %>
		</div>
	</div>
	<div class="logo">
		<div>
			<%= link_to image_tag('/assets/golden_dragon.png'), root_path %>
		</div>
	</div>
	<h1>Chinese Restaurant</h1>
	<div class="menuWaypoint menuWayTop"></div>
	<div class="menuWaypoint menuWayMid"></div>
	<div class="menuWaypoint menuWayBot"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= title %></title>
		<%= stylesheet_link_tag 'all/application' %>
		<!--[if !IE]><!-->
			<%= stylesheet_link_tag 'nonie/application' %>
		<!--<![endif]-->
		<!--[if gte IE 9]>
			<%= stylesheet_link_tag 'nonie/application' %>
		<![endif]-->
		<!--[if lt IE 9]>
			<%= stylesheet_link_tag 'ie/application' %>
		<![endif]-->
		<%= stylesheet_link_tag    "print/application", media: :print %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<%= favicon_link_tag 'favicon.ico' %>
		<meta charset="UTF-8">
		<meta property="og:title" content="Golden Dragon Restaurant">
		<meta property="og:image" content="http://menyou.herokuapp.com/assets/logo.png">
		<meta property="og:site_name" content="Golden Dragon">
		<meta property="og:description" content="<%= meta_description %>">
		<%= yield :head %>
		<script>
		// Facebook
		(function(d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) return;
			js = d.createElement(s); js.id = id;
			js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=160257407449032";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
		// Twitter
		!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
		</script>
	</head>
	<body>
		<div id="fb-root"></div>
		<div class="wrapper">
			<div class="header">
				<%= render 'layouts/header' %>
			</div>
			<div class="content">
				<% flash.each do |key, value| %>
					<div class="flash <%= key %>">
						<%= link_to image_tag('/assets/close.png'), '#', class: 'closeFlash', title: "Close" %>
						<p><%= value %></p>
					</div>
				<% end %>
				<%= yield %>
			</div>
		</div>
		<div class="footer">
			<%= render 'layouts/footer' %>
		</div>
		<div class="commentForm">
			<%= render 'comments/comment_form' %>
		</div>
	</body>
</html>